version: "3.9"

services:
  core-mock:
    image: golang:1.23
    working_dir: /workspace
    command: ["go", "run", "./deployment/localdev/mock-core"]
    volumes:
      - ../..:/workspace
    environment:
      GO111MODULE: "on"
    ports:
      - "8080:8080"

  valkey:
    image: valkey/valkey:8.0-alpine
    command: ["valkey-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  weaviate:
    image: semitechnologies/weaviate:1.25.7
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "none"
      CLUSTER_HOSTNAME: "node1"
      DISABLE_TELEMETRY: "true"
    ports:
      - "8081:8080"
    volumes:
      - weaviate-data:/var/lib/weaviate

  mirador-rca:
    image: golang:1.23
    depends_on:
      - core-mock
      - valkey
      - weaviate
    working_dir: /workspace
    command: ["go", "run", "./cmd/rca-engine", "--config", "deployment/localdev/config/mirador-rca.yaml"]
    environment:
      GO111MODULE: "on"
    volumes:
      - ../..:/workspace
    ports:
      - "50051:50051"
      - "2112:2112"

volumes:
  weaviate-data:
