apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: mirador-rca
  labels:
    app.kubernetes.io/component: valkey
    app.kubernetes.io/name: mirador-rca
spec:
  serviceName: valkey
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: valkey
      app.kubernetes.io/name: mirador-rca
  template:
    metadata:
      labels:
        app.kubernetes.io/component: valkey
        app.kubernetes.io/name: mirador-rca
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-auth
                  key: password
            - name: VALKEY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: valkey-auth
                  key: username
          command:
            - valkey-server
            - --requirepass
            - $(VALKEY_PASSWORD)
            - --protected-mode
            - "no"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/component: valkey
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
