apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-data
  namespace: mirador-rca
  labels:
    app.kubernetes.io/component: weaviate
    app.kubernetes.io/name: mirador-rca
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
