apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: mirador-rca
  labels:
    app.kubernetes.io/component: weaviate
    app.kubernetes.io/name: mirador-rca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: weaviate
      app.kubernetes.io/name: mirador-rca
  template:
    metadata:
      labels:
        app.kubernetes.io/component: weaviate
        app.kubernetes.io/name: mirador-rca
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:1.25.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "false"
            - name: DISABLE_TELEMETRY
              value: "true"
            - name: DEFAULT_VECTORIZER_MODULE
              value: "none"
            - name: ENABLE_MODULES
              value: "none"
          volumeMounts:
            - name: data
              mountPath: /var/lib/weaviate
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: weaviate-data
