apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: valkey
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          command:
            - valkey-server
            - --requirepass
            - $(VALKEY_PASSWORD)
            - --appendonly
            - "yes"
            - --protected-mode
            - "no"
