server:
  address: ":50051"
  gracefulTimeout: 10s

clients:
  core:
    baseURL: "https://mirador-core.internal"
    metricsPath: "/api/v1/rca/metrics"
    logsPath: "/api/v1/rca/logs"
    tracesPath: "/api/v1/rca/traces"
    serviceGraphPath: "/api/v1/rca/service-graph"
    timeout: 5s

weaviate:
  endpoint: "https://weaviate.cluster.internal"
  apiKey: ""
  timeout: 5s

cache:
  addr: ""
  db: 0
  similarIncidentsTTL: 2m
  serviceGraphTTL: 5m
  maxRetries: 2
  tls: false

logging:
  level: "info"
  json: false

rules:
  path: "configs/rules/default.yaml"
